### ISSUE TITLE
Inconsistency in panicking string methods and truncating ones

### ISSUE THREAD

**Issue by paulocsanz** [slightlyoutofphase/staticvec#34]
The API is inconsistent about panicking.

`push`, `push_str` and `insert` panic, but `insert_str`, `from_chars`, `from_str`, `from_utf8`, `from_utf16` default to truncating.

It would make sense making the others panic and add a `truncating` alternative, or drop the panicking ones all together (what was done in the original implementation). It may be a little less ergonomic to panic by default, but it also allows for a library that you know will never panicking, making it much more useful in embed systems (except for `Index`es traits).

It's a though trade-off tho, since this is a breaking change, it may have to wait for 8.0 (but this can be documented).

Also, the `remove` method doesn't panic, but the docs says it does. (it panics in debug only, but it really shouldn't, not if it returns `Result`, actually, checking the code, a bunch of `debug_assertions` can be dropped, since they are basically checking that functions like `is_char_boundary` or `is_inside_boundary` work), `debug_assertions` are great to discover UB before it happens.

**Comment by slightlyoutofphase** [comment]
Yeah I'm kind of in the process of switching them over to mostly panic (since that's close to what `String`  does, and also what most other fixed-capacity string crates usually do.)

As far as the debug assertions you had in a lot of the methods, I've definitely been realizing a lot of them aren't needed and removing them.

Version 0.8.0 of the crate (which I'll probably release in the next couple of days) will have the API finalized.
