### ISSUE TITLE
Implement `core::fmt::Write` for `StaticVec`

### ISSUE THREAD

**Issue by Ayrx** [slightlyoutofphase/staticvec#52]
`StaticVec` currently implements `std::io::Write` when `std` is enabled. If it supports `core::fmt::Write`, consumers of the type can use the vector as a target for formatting in a `no_std` environment.

**Comment by slightlyoutofphase** [comment]
Good call. Not actually sure why I didn't think to do this previously, honestly. Will give it a look today, seems rather trivial.

**Comment by slightlyoutofphase** [comment]
Alright, I've now added this. One thing I will note is that depending on what your use case actually is, you might want to consider using `StaticString` (which did actually already have a `core::fmt::Write` impl) rather than `StaticVec` directly.

That said, I still felt that adding this for `StaticVec` was the way to go as it allowed me to just have the `StaticString` version defer directly to it, which is definitely at least somewhat more performant overall. Thanks for the suggestion!
